name: meditate

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: The prompt to generate completions for.
        required: true

jobs:
  openai_completion:
    runs-on: ubuntu-latest
    name: OpenAI
    steps:
      - uses: austenstone/openai-completion-action@main
        name: OpenAI Completion
        id: openai_completion
        with:
          prompt: ${{ github.event.inputs.prompt }}
          finish_reason: stop
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - uses: actions/github-script@v5
        name: Print the response text
        with:
          script: console.log(JSON.parse('${{ steps.openai_completion.outputs.response }}'))

      - uses: actions/checkout@v2
      - name: tick
        run: |
          echo "${{ steps.openai_completion.outputs.response }}" > test.json
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git add test.json
          git commit -m "add test response"
          git push origin main
