name: meditate

on:
  push:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:
    inputs:
      prompt:
        description: Please provide a prompt for completion.
        required: true

jobs:
  meditate:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      CUSTOM_PROMPT: ${{ github.event.inputs.prompt }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: npm install

      - name: meditation
        id: meditation
        run: npm start

      - uses: actions/checkout@v2
      - name: commit
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"

          echo -e "# ${{ steps.meditation.outputs.commitMsg }}\n" > "${{ steps.meditation.outputs.fileName }}"
          echo -e ${{ steps.meditation.outputs.response }} >> "${{ steps.meditation.outputs.fileName }}"
          echo -e "\n> ${{ steps.meditation.outputs.engine_id }}, $(date +"%A, %H:%M %Z, %F")" >> "${{ steps.meditation.outputs.fileName }}"

          echo -e "[${{ steps.meditation.outputs.baseName }}](${{ steps.meditation.outputs.fileName }})\n" >> README.md

          git add "${{ steps.meditation.outputs.fileName }}"
          git add README.md

          git commit -m "${{ steps.meditation.outputs.commitMsg }}"
          git push origin $(git rev-parse --abbrev-ref HEAD)
